[package]
name = "gtakeout"
version = "0.1.0"
edition = "2024"
license = "WTFPL"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
kamadak-exif = "0.5"
chrono = "0.4"
rayon = "1.10"
